[tools]
python = "3.12"
vercel = "latest"

[tasks.install]
description = "Install dependencies from pyproject.toml"
# The '.' tells pip to install the current project and its dependencies
run = "pip install ."

[tasks.generate]
description = "Run the QR generator"
run = "python generate.py"